name: Artwork Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: CheckoutRepo
          uses: actions/checkout@v4

        - name: Run script
        - name: Upload dron file
          uses: actions/upload-artifact@v4
          with:
            name: Upload a my dragon
            path: dragon.txt 
