name: Sample Workflow

on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: CheckoutRepo
          uses: actions/checkout@v4

        - name: List file
          run: ls

        - name: Readfile
          run: cat README.md

